### ISSUE TITLE
SplitBuilderParams

### ISSUE THREAD

**Issue by zakhvataev** [educauchy/abacus#22]
В SplitBuilderParams в атрибуте map_group_names_to_sizes, при изменении поля "control"  на что либо ещё, вываливается ошибка на шаге запуска SplitBuilder.
![image](https://user-images.githubusercontent.com/61847990/215490821-0e0e9e2a-01d9-4d9f-9900-caefb57e63a4.png)
![image](https://user-images.githubusercontent.com/61847990/215491571-83c863ce-aff9-43b2-bdd1-25bc374df04f.png)

**Comment by educauchy** [comment]
See the new repository.
